#cloud-config

preserve_hostname: true

package_update: true
packages:
  - bind9-dnsutils
  - command-not-found
  - conntrack
  - ipset
  - jq
  - lsof
  - mg
  - parallel
  - qemu-guest-agent
  - rsync
  - silversearcher-ag
  - strace
  - tmux
  - xterm

bootcmd:
- cloud-init-per once ssh-ca echo "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pub" >> /etc/ssh/sshd_config.d/50-trusted-user-ca-keys.conf

runcmd:
  - systemctl enable --now qemu-guest-agent

write_files:
  - path: /etc/skel/.hushlogin
    owner: root:root
